name = "line-bot"
main = "worker.js"
compatibility_date = "2023-12-18"

# KV Namespace binding
kv_namespaces = [
  { binding = "CHAT_HISTORY", id = "ed0b0e4d71644b579cc15d04b5b8ef6b" }
]

[vars]
# 這裡的值會被實際的環境變數覆蓋
LINE_CHANNEL_ACCESS_TOKEN = "a7NFdDpVUOxVpRLMQni1h89nIS74nALEpS2GKMJkd1uq5BhGtCoQmZokTDRiL+7bg9Weyw2aQYniZ4MulKOauAVBJ0XEFWOXtGK5uP4O8AYjg8KV74fLiRV6nGVw9IKZO8Cjq8RxkIXP5Q3dIHhf6gdB04t89/1O/w1cDnyilFU="
LINE_CHANNEL_SECRET = "f156b87508fe9e311d9ede9cc3aa5807"
GROQ_API_KEY = "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"

[observability.logs]
enabled = true
